# Generated by Django 5.0.3 on 2024-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_company_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering Department'), ('Product Management', 'Product Management Department'), ('Quality Assurance', 'Quality Assurance Department'), ('Design', 'Design Department'), ('Sales', 'Sales Department'), ('Marketing', 'Marketing Department'), ('Human Resources', 'Human Resources Department'), ('Finance', 'Finance Department'), ('Customer Support', 'Customer Support Department'), ('Operations', 'Operations Department')], max_length=100, null=True),
        ),
    ]
