# Generated by Django 5.0.3 on 2024-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_device_assigndevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='condition',
        ),
    ]
