# Generated by Django 5.0.3 on 2024-03-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_device_condition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignDevice',
            new_name='AllocationDevice',
        ),
    ]
