# Generated by Django 5.0.3 on 2024-03-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_deviceconditionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconditionlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
